appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kvwzysSdxY6Uf8Kgnu3TKlYKVy0u5T5+iEuh6YCkahqet8M8AZkd+MUhdrl7q/NKJnMDqemk82Mbv2H8QlT2JpZbFlPqY346pwFRpZCrBF/q70W/JV9Yx+c041l/CXzoTPgvbcglmABsFWYSVnLl7xRsmqHwNejhKuX5KYXdBSGfWo9P6SDF0S9oOrPAYAQ+1ZOfxBGtIyNhuyi2rreLzlWMBs9vFDCzEuJyNTBFi98eo3wt7CxCSNnNQBCQf34LgILL9FWmqTumPFAPu8xLqvK8OS4VB0Rl4K61LWk4B5fKsoM1iRyke8rI0ev1hgTia6Wu1tb2dMfxwKEY5iirWbVrQrL/G0qHIYvG5U7Nuu65MHyvcnyOnHqkPOWHtB8uYP/18zJmgiDJd2B47N9MZMwDCC6HsuSsHklqRQzsD9DFHoEguwDpkH1KWIncnS0OazOnTXHddSSfIr+UKsFAXUP6v7BS1O1Q7BlDo+BkfzaEaGQ3h7CtzYsQ8bJPxltlL0+VOz9TIS8aWImtpDcbN+5Vnnn0a8m12CICrR1jgks56DrXhoKibE1EnICvr/7jaoOfQDipF8RIORJoNFtNnyClgfwyUYJ+S2G5XTMeQJcjgCXtk9AxSaWfnaIxjktW9MiaCyPGCYnUwgmbO8zWZXxuRu/JoxHeHvHJdYPLbWU=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
